######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 14 15:19:21 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QMAKE_LFLAGS += -Wl,--rpath=\\\$\$ORIGIN/lib
# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
RESOURCES += qml.qrc
